server:
  context-path: /auction
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: hr
    password: hr
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
    encoding:
      charset: utf-8
      force: true
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/dao/*Mapper.xml
